twitnerario/apps/registros/urls.py
# -*- coding: UTF8 -*-
from django.conf.urls.defaults import *

urlpatterns = patterns('registros.views',
    url(r'^$', 'registro', name='registro'),
    url(r'^(?P<ponto>\d+)', 'registro_ponto', name='registro_ponto'),
)

twitnerario/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.conf import settings
from django.contrib import admin
from twitterauth.views import twitter_signin, twitter_return
from core.tweet import localizar, pontos, linhas, send_tweets
from registros.views import pesquisar
admin.autodiscover()

urlpatterns=patterns('',
    url(r'^admin/', include(admin.site.urls)),
    
    #url(r'^pesquisar/', pesquisar, name='pesquisar'),
    url(r'^$', pesquisar, name='pesquisar'),
    url(r'^registro/', include('registros.urls', namespace='registro')),
    url(r'^login/$', twitter_signin, name='login'),
    url(r'^return/$', twitter_return, name='return'),
    url(r'^localizar/(.+)/$', localizar, name='localizar'),
    url(r'^pontos/$', pontos, name='pontos'),
    url(r'^(\d+)/linhas/$', linhas, name='linhas'),
    url(r'^facebookauth/$', direct_to_template,
        {'template': 'facebook_auth/facebook_auth.html'},
        name='facebook_auth'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
            { 'document_root': settings.MEDIA_ROOT }),
    )

twitnerario/apps/registros/models.py
# -*- coding: UTF8 -*-

from django.db import models
from registros.model_choices import HORAS, MINUTOS, LEMBRAR


class Registros(models.Model):
    """
    Você será mencionado em um tweet (@twitnerario)
    com o horário aproximado do seu ônibus.
    """
    criado_em = models.DateTimeField('criado em', auto_now_add=True)
    twitter = models.CharField('twitter', max_length=15)
    ponto = models.CharField(u'ponto', max_length=4)
    linha = models.CharField(u'linha', max_length=6)
    horas = models.PositiveSmallIntegerField(u'quero ser lembrado às',
        choices=HORAS, default=7)
    minutos = models.PositiveSmallIntegerField(u':', choices=MINUTOS,
        default=0)
    lembrar = models.PositiveSmallIntegerField(u'me lembre',
        choices=LEMBRAR, default=0)
    fim_de_semana = models.BooleanField(u'incluir fim de semana?',
        default=False)
    falhou = models.BooleanField(u'falhou?', default=False)

    class Meta:
        verbose_name = u"Registro"

    def __unicode__(self):
        return self.twitter

twitnerario/apps/registros/forms.py
# -*- coding: UTF8 -*-

from django import forms
from django.forms import ModelForm
from form_utils.forms import BetterModelForm
from registros.models import Registros


class RegistrosForm(BetterModelForm):
    class Meta:
        model = Registros
        widgets = {
            'linha': forms.Select(),
            'fim_de_semana': forms.TextInput(attrs={'style': 'display:none'}),
        }
        fieldsets = [
                   ('Registro', {
                   'fields': [
                              'twitter',
                              'ponto',
                              'linha',
                              'horas',
                              'minutos',
                              'lembrar',
                              'fim_de_semana',
                              ],
                   'classes': ['registro']
                   })
                 ]
        row_attrs = {
        }

twitnerario/apps/registros/views.py
# -*- coding: UTF8 -*-

from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, get_object_or_404
from django.template import Context, RequestContext
from registros.models import Registros
from registros.forms import RegistrosForm
from django.http import HttpResponse, HttpResponseRedirect


def salvar_registro(request, form):
    t = request.POST['twitter'] or None
    l = request.POST['linha'] or None
    p = request.POST['ponto'] or None
    h = int(request.POST['horas'] or None)
    m = int(request.POST['minutos'] or None)

    # se duplicado então remove o anterior
    rs = Registros.objects.filter(twitter=t, ponto=p, linha=l,
                                    horas=h, minutos=m)
    if rs.count() > 0:
        rs.delete()

    form.save()

    return render_to_response('registros/sucesso.html',
        context_instance=RequestContext(request,
            {'twitter': t, 'm': m, 'h': h}))


def registro(request):
    """
    Recebe formulario e registra tweet
    """

    #rs = Registros.objects.none()
    form = RegistrosForm(request.POST or None)
    if form.is_valid():
        return salvar_registro(request, form)

    return render_to_response('registros/registro.html',
        context_instance=RequestContext(request, {'form': form}))


def registro_ponto(request, ponto):
    """
    Recebe numero do ponto e preenche o formulario
    """
    form = RegistrosForm(initial={'ponto': ponto})

    if request.method == 'POST':
        form = RegistrosForm(request.POST)

    if form.is_valid():
        return salvar_registro(request, form)

    return render_to_response('registros/registro.html',
        context_instance=RequestContext(request, {'form': form}))


def pesquisar(request):
    """
    Redireciona para o template pesquisar ponto
    """
    return render_to_response('pesquisar/pesquisar.ponto.html',
        context_instance=RequestContext(request))

twitnerario/templates/registros/registro.html
{% extends "base.html" %}
{% block content %}
  <style>
    .ui-combobox {
        position: relative;
        display: inline-block;
    }
    .ui-combobox-toggle {
        position: absolute;
        top: 0;
        bottom: 0;
        margin-left: -1px;
        padding: 0;
        /* adjust styles for IE 6/7 */
        *height: 1.7em;
        *top: 0.1em;
    }
    .ui-combobox-input {
        margin: 0;
        padding: 0.3em;
    }
  </style>
  <link rel="stylesheet" href="{{ MEDIA_URL }}css/overcast/jquery-ui-1.8.18.custom.css" type="text/css" charset="utf-8">
  <script type="text/javascript" src="{{MEDIA_URL}}js/prototype.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}js/pontos-array.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}js/titlecase.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}js/twitnerario.registro.js"></script>
  <script type="text/javascript">
  jQuery(function() {
    jQuery("select#combobox_localizar").combobox();
    jQuery("select#combobox_localizar").bind( "autocompleteopen", function(event, ui) {
      alert('click');
    });
  });
  </script>
  <div class="row">
      <div class="span16">
      <form action="" method="post" style="margin-bottom: 10px;">{% csrf_token %}
        <fieldset style="margin-bottom: 10px;">
          <legend>Agendar tweet</legend>
          <div class="clearfix">
            {{ form.twitter.label_tag }}
            <div class="input">
                <div class="input-prepend">
                  <span class="add-on">@</span>
                {{ form.twitter }}
                </div>
            </div>
          </div>
          <!-- Localizar -->
          <!-- <div class="clearfix">
            <label for="id_localizar">Localizar</label>
            <div class="input">
              <div class="ui-widget">
                <select id="combobox_localizar">
                  <option value="">Select one...</option>
                  <option value="momo">ActionScript</option>
                  <option value="AppleScript">AppleScript</option>
                  <option value="Asp">Asp</option>
                  <option value="BASIC">BASIC</option>
                  <option value="C">C</option>
                </select>
                </div>
            </div>
          </div> -->
          <div class="clearfix">
            {{ form.ponto.label_tag }}
            <div class="input">
              <div class="input-prepend">
                <span class="add-on">Nº</span>
                  {{ form.ponto }}
                </div>
            </div>
          </div>
          <div class="clearfix">
            {{ form.linha.label_tag }}
            <div class="input">
                {{ form.linha }}
            </div>
          </div>
          <div class="hour clearfix">
            {{ form.horas.label_tag }}
            <div class="input">
                {{ form.horas }} : {{ form.minutos }}
            </div>
          </div>
          <div class="hour clearfix">
            {{ form.lembrar.label_tag }}
            <div class="input">
              {{ form.lembrar }}
            </div>
          </div>
          <div class="hour clearfix">
            {#{ form.fim_de_semana.label_tag }#}
            <div class="input">
                {{ form.fim_de_semana }}
            </div>
          </div>
          <div class="actions">
            <input class="btn primary" type="submit" value="Salvar Ponto">
            <a class="btn" href="/twitnerario/">Cancelar</a>
          </div>
              </fieldset>
          </form>
      </div>
  </div>
  <div class="row">
      <div id="content" class="span16"></div>
  </div>
{% endblock %}
{% block footer_inc %}
<script type="text/javascript" src="{{MEDIA_URL}}js/encontra-linhas.js"></script>
{% endblock %}

twitnerario/templates/registros/registro_source.html
<h3>Registro</h3>
<!-- Formulario -->
<form action="#" method="post" class="form"><div style='display:none'><input type='hidden' name='csrfmiddlewaretoken' value='06ee6b2090216562641bef85da01cf29' /></div>
  





<fieldset class="fieldset_Registro first">

<legend>Registro</legend>

<ul>



<li class="required">
  
  <label for="id_twitter">
  Twitter
  
  </label>
  <input id="id_twitter" type="text" name="twitter" value="@morenocunha" maxlength="15" />
</li>



<li class="required">
  
  <label for="id_ponto">
  Ponto número
  
  </label>
  <input type="text" name="ponto" value="5024" id="id_ponto" />
</li>



<li class="required">
  
  <label for="id_linha">
  Linha
  
  </label>
  <input type="text" name="linha" value="202" id="id_linha" />
</li>



<li class="required">
  
  <label for="id_horas">
  Estou no ponto às
  
  </label>
  <select name="horas" id="id_horas">
<option value="0">00</option>
<option value="1">01</option>
<option value="2">02</option>
<option value="3">03</option>
<option value="4">04</option>
<option value="5">05</option>
<option value="6">06</option>
<option value="7" selected="selected">07</option>
<option value="8">08</option>
<option value="9">09</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
</select>
</li>



<li class="required">
  
  <label for="id_minutos">
  :
  
  </label>
  <select name="minutos" id="id_minutos">
<option value="0" selected="selected">00</option>
<option value="15">15</option>
<option value="30">30</option>
<option value="45">45</option>
</select>
</li>




</ul>
</fieldset>



  <div class="buttons">
    <input class="button" src="button" type="submit" value="Salvar">     
    <a class="button" src="button" href="#">Voltar</a>
  </div>  
</form>
<div id='content'></div>
<script src="http://code.jquery.com/jquery-1.6.4.min.js" type="text/javascript"></script>
<script>
$(function(){
                $.getJSON('http://rast.vitoria.es.gov.br/pontovitoria/utilidades/listaPontos', 
                function(data){
                    var markup = data;
                    $("#content").html(data);
                });
    });
</<script>

twitnerario/templates/registros/sucesso.html
{% extends "base.html" %}
{% block page_title %}Sucesso! - {% endblock %}

{% block content %}
	<div class="row">
		<div class="span8">
			<div class="alert-message block-message success">
				<a href="#" class="close">×</a>
				<p><strong>Sucesso!</strong></p>
				<p>{{ twitter }} às {{ h }}:{% if m == 0 %}00{% else %}{{ m }}{% endif %} horas você será mencionado em um tweet (@twitnerario) com o horário aproximado do seu ônibus.</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="span8">
			<a href="/" class="btn">Voltar</a>
		</div>
	</div>
{% endblock %}